from src.presentation_generation.nodes.orchestrator_node import OrchestratorNode
from src.presentation_generation.nodes.slide_worker_node import SlideWorkerNode
from src.presentation_generation.nodes.aggregator_node import AggregatorNode